name: Deploy Vue.js Project to GitHub Pages

on:
  push:
    branches:
      - main # Cambia esto a la rama que quieras usar para hacer el deploy

jobs:
  build:
    runs-on: ubuntu-latest

    env: # Establece la variable de entorno aquí
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Esta acción ya está en la versión correcta

      - name: Use Node.js v20.15.0
        uses: actions/setup-node@v3
        with:
          node-version: "20.15.0"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # Asegúrate de que sea la última versión
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
